dataset:
  root: data/datasets/crowd_dataset

input:
  clip_length: 16
  fps: 8
  resolution: 224

model:
  type: "I3D"
  input_channels: 3
  num_classes: 2
  checkpoint_path: "data/models/violence_i3d_rgb.pt"

training:
  batch_size: 4  # Reduced for CPU training
  epochs: 50
  learning_rate: 1e-4
  weight_decay: 1e-4
  early_stopping_patience: 10

